services:
  web:
    container_name: temuruang-web
    build:
      context: .
      dockerfile: deploy/Dockerfile
    networks:
      - temuruangweb
  proxy:
    container_name: temuruang-proxy-web 
    image: nginx:stable-alpine
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - temuruangweb
    ports:
      - '80:80'

networks:
  temuruangweb:
    driver: bridge